/** Typed package-local visible editor copy (§35). Authored theme text,
 * telemetry values and developer errors stay outside this module. */
export const uiCopy = {
  brand: "Vigilia",
  editor: "Editor",
  rail: {
    layers: "Layers",
    add: "Add",
    assets: "Assets",
    settings: "Settings",
  },
  /** Compact rail marks; the accessible name is the full label. */
  railMark: {
    layers: "▤",
    add: "+",
    assets: "▣",
    settings: "⚙",
  },
  inspector: { design: "Design", data: "Data", style: "Style" },
  /** Selection inspector field labels. */
  inspectorFields: {
    selection: "Selection",
    x: "X",
    y: "Y",
    width: "Width",
    height: "Height",
    rotation: "Rotation",
    /** Row labels for the inspector's paired geometry lines. */
    position: "Position",
    size: "Size",
    invalidValue: "That value cannot be applied to the selection.",
    nothingSelected: "Select an object to inspect it.",
    opacity: "Opacity %",
    paint: "Paint",
    notSet: "not set",
    unresolved: "no longer resolves",
    runs: "Runs",
    runPreset: "Type preset",
    editTypePresets: "Edit type presets",
    documentStyle: "This document",
    runColour: "Colour",
    runSource: "Reads",
    staticText: "Static text",
    runFormat: "Format",
    runZone: "Zone",
    runZoneFollows: "Follow the display",
    valueRun: "Value",
    emptyRun: "(empty)",
    align: "Align",
    left: "Left",
    centre: "Centre",
    right: "Right",
    wrap: "Wrap",
    on: "On",
    off: "Off",
    overflow: "Overflow",
    clip: "Clip",
    ellipsis: "Ellipsis",
    overflowVisible: "Visible",
  },
  menus: {
    file: "File",
    edit: "Edit",
    insert: "Insert",
    arrange: "Arrange",
    view: "View",
  },
  file: {
    newDocument: "New",
    openPackage: "Open package",
    savePackage: "Save package",
    releasePackage: "Release package",
    openLibrary: "Open library",
    saveLibrary: "Save to library",
  },
  view: {
    dataSource: "Data source",
    chartRefresh: "Chart refresh",
    preview: "Preview",
    live: "Live",
    valueRuns: "Value runs",
    tokens: "tokens",
    values: "values",
  },
  actions: {
    duplicate: "Duplicate",
    lock: "Lock",
    unlock: "Unlock",
    front: "Bring to front",
    bringForward: "Bring forward",
    sendBackward: "Send backward",
    back: "Send to back",
    group: "Group",
    ungroup: "Ungroup",
    align: "Align left",
    distribute: "Distribute horizontally",
    delete: "Delete",
    undo: "Undo",
    redo: "Redo",
    copy: "Copy",
    cut: "Cut",
  },
  /** One label per arrange action; keys mirror `ArrangeAction`. */
  arrangeLabels: {
    "align-left": "Align left",
    "align-center-x": "Centre horizontally",
    "align-right": "Align right",
    "align-top": "Align top",
    "align-center-y": "Centre vertically",
    "align-bottom": "Align bottom",
    "distribute-x": "Distribute horizontally",
    "distribute-y": "Distribute vertically",
  },
  dock: { label: "Selected object actions" },
  /** The canvas context menu's accessible name. Its entries reuse the action
   * registry's labels and `chartFamilies`, so no entry copy lives here. */
  canvasMenu: { label: "Canvas actions" },
  /** The stage toolbar's accessible name; the eight buttons carry the labels. */
  arrangeToolbar: { label: "Arrange the selection" },
  /** The stage camera's readout; `label` is also the control's accessible name. */
  zoom: {
    label: "Zoom level",
    toFit: "Zoom to fit",
    toSelection: "Zoom to selection",
    actualSize: "100 %",
  },
  palette: "Shell palette",
  /** Chart family labels, shared by the Add panel and the Insert menu. */
  chartFamilies: {
    gauge: "Gauge",
    line: "Line",
    bar: "Bar",
    pie: "Pie",
  },
  /** Panel copy. Panel factories own their DOM contract; this owns the words. */
  panels: {
    layers: "Layers",
    /** Layer-tree row controls. The twisty and the rename field carry the
     * layer's name as well, so those two names are unique; the state icons do
     * not, because "Hide" on every row is the same control repeated and the row
     * it sits in is what tells them apart. */
    hide: "Hide",
    show: "Show",
    rename: "Rename",
    collapse: "Collapse",
    expand: "Expand",
    add: "Add",
    text: "Text",
    assets: "Assets",
    removeAsset: "Remove asset",
    themeSettings: "Theme settings",
    previewFit: "Preview fit",
    backgroundMedia: "Background media",
    mediaFit: "Media fit",
    releaseVersion: "Release version",
    notSet: "Not set",
    none: "None",
    /** Shown by a numeric field when an edit is refused, whether it could not be
        read as a number or fell outside the field's range. */
    invalidNumber: "That value cannot be applied. Enter a number in range.",
    palette: "Palette",
    paint: "Paint",
    addColour: "Add colour",
    addStop: "Add stop",
    deleteColour: "Delete colour",
    reassign: "Reassign to",
    typePresets: "Type presets",
    addType: "Add type",
    deleteType: "Delete type",
    previewFont: "Preview font",
    applyFont: "Apply font",
    applyTrio: "Apply trio",
    unitDisplay: "Unit display",
    selectChart: "Select a chart to edit its settings.",
    /** Field labels shared by more than one panel. */
    name: "Name",
    author: "Author",
    description: "Description",
    /** A paired width/height row has no room for the full words beside both
        boxes, so the row keeps its "Size" label and marks them W and H. */
    widthMark: "W",
    heightMark: "H",
    background: "Background",
    barColour: "Bar colour",
    family: "Family",
    size: "Size",
    weight: "Weight",
    lineHeight: "Line height",
    letterSpacing: "Letter spacing",
    font: "Font",
    trio: "Trio",
  },
} as const;
