/** Typed package-local visible editor copy (§35). Authored theme text,
 * telemetry values and developer errors stay outside this module. */
export const uiCopy = {
  brand: "Vigilia",
  editor: "Editor",
  rail: {
    layers: "Layers",
    add: "Add",
    assets: "Assets",
    settings: "Settings",
  },
  /** Compact rail marks; the accessible name is the full label. */
  railMark: {
    layers: "▤",
    add: "+",
    assets: "▣",
    settings: "⚙",
  },
  inspector: { design: "Design", data: "Data", style: "Style" },
  menus: {
    file: "File",
    edit: "Edit",
    insert: "Insert",
    arrange: "Arrange",
    view: "View",
  },
  file: {
    newDocument: "New",
    openPackage: "Open package",
    savePackage: "Save package",
    releasePackage: "Release package",
    openLibrary: "Open library",
    saveLibrary: "Save to library",
  },
  view: {
    dataSource: "Data source",
    chartRefresh: "Chart refresh",
    preview: "Preview",
    live: "Live",
  },
  actions: {
    duplicate: "Duplicate",
    lock: "Lock",
    unlock: "Unlock",
    front: "Bring to front",
    bringForward: "Bring forward",
    sendBackward: "Send backward",
    back: "Send to back",
    group: "Group",
    ungroup: "Ungroup",
    align: "Align left",
    distribute: "Distribute horizontally",
    delete: "Delete",
    undo: "Undo",
    redo: "Redo",
    copy: "Copy",
    cut: "Cut",
  },
  dock: { label: "Selected object actions" },
  palette: "Shell palette",
  /** Chart family labels, shared by the Add panel and the Insert menu. */
  chartFamilies: {
    gauge: "Gauge",
    line: "Line",
    bar: "Bar",
    pie: "Pie",
  },
  /** Panel copy. Panel factories own their DOM contract; this owns the words. */
  panels: {
    layers: "Layers",
    arrange: "Arrange",
    add: "Add",
    text: "Text",
    assets: "Assets",
    removeAsset: "Remove asset",
    themeSettings: "Theme settings",
    previewFit: "Preview fit",
    backgroundMedia: "Background media",
    mediaFit: "Media fit",
    releaseVersion: "Release version",
    notSet: "Not set",
    none: "None",
    palette: "Palette",
    paint: "Paint",
    addColour: "Add colour",
    addStop: "Add stop",
    deleteColour: "Delete colour",
    reassign: "Reassign to",
    typePresets: "Type presets",
    addType: "Add type",
    deleteType: "Delete type",
    previewFont: "Preview font",
    applyFont: "Apply font",
    applyTrio: "Apply trio",
    unitDisplay: "Unit display",
    selectChart: "Select a chart to edit its settings.",
    /** Field labels shared by more than one panel. */
    name: "Name",
    author: "Author",
    description: "Description",
    width: "Width",
    height: "Height",
    background: "Background",
    barColour: "Bar colour",
    family: "Family",
    size: "Size",
    weight: "Weight",
    lineHeight: "Line height",
    letterSpacing: "Letter spacing",
    font: "Font",
    trio: "Trio",
  },
} as const;
